# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class InvoiceDto(BaseModel):
    """
    InvoiceDto
    """ # noqa: E501
    id: Optional[StrictInt]
    name: Optional[StrictStr]
    document_number: Optional[StrictStr] = Field(alias="documentNumber")
    organization_subscription_id: Optional[StrictInt] = Field(alias="organizationSubscriptionId")
    is_paid: Optional[StrictBool] = Field(alias="isPaid")
    required_payment_action: Optional[StrictBool] = Field(alias="requiredPaymentAction")
    stripe_invoice_id: Optional[StrictStr] = Field(alias="stripeInvoiceId")
    price: Union[StrictFloat, StrictInt]
    start_date: datetime = Field(alias="startDate")
    end_date: datetime = Field(alias="endDate")
    due_date: datetime = Field(alias="dueDate")
    __properties: ClassVar[List[str]] = ["id", "name", "documentNumber", "organizationSubscriptionId", "isPaid", "requiredPaymentAction", "stripeInvoiceId", "price", "startDate", "endDate", "dueDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if document_number (nullable) is None
        # and model_fields_set contains the field
        if self.document_number is None and "document_number" in self.model_fields_set:
            _dict['documentNumber'] = None

        # set to None if stripe_invoice_id (nullable) is None
        # and model_fields_set contains the field
        if self.stripe_invoice_id is None and "stripe_invoice_id" in self.model_fields_set:
            _dict['stripeInvoiceId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "documentNumber": obj.get("documentNumber"),
            "organizationSubscriptionId": obj.get("organizationSubscriptionId"),
            "isPaid": obj.get("isPaid"),
            "requiredPaymentAction": obj.get("requiredPaymentAction"),
            "stripeInvoiceId": obj.get("stripeInvoiceId"),
            "price": obj.get("price"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "dueDate": obj.get("dueDate")
        })
        return _obj


