# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class KeycloakListDto(BaseModel):
    """
    KeycloakListDto
    """ # noqa: E501
    id: Optional[StrictInt]
    name: Optional[StrictStr]
    url: Optional[StrictStr]
    client_id: Optional[StrictStr] = Field(alias="clientId")
    client_secret: Optional[StrictStr] = Field(alias="clientSecret")
    realms_name: Optional[StrictStr] = Field(alias="realmsName")
    organization_id: Optional[StrictInt] = Field(alias="organizationId")
    organization_name: Optional[StrictStr] = Field(alias="organizationName")
    partner_logo: Optional[StrictStr] = Field(alias="partnerLogo")
    enabled: Optional[StrictBool]
    __properties: ClassVar[List[str]] = ["id", "name", "url", "clientId", "clientSecret", "realmsName", "organizationId", "organizationName", "partnerLogo", "enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KeycloakListDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if partner_logo (nullable) is None
        # and model_fields_set contains the field
        if self.partner_logo is None and "partner_logo" in self.model_fields_set:
            _dict['partnerLogo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeycloakListDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "url": obj.get("url"),
            "clientId": obj.get("clientId"),
            "clientSecret": obj.get("clientSecret"),
            "realmsName": obj.get("realmsName"),
            "organizationId": obj.get("organizationId"),
            "organizationName": obj.get("organizationName"),
            "partnerLogo": obj.get("partnerLogo"),
            "enabled": obj.get("enabled")
        })
        return _obj


