# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from taikunpycore.models.common_dropdown_dto import CommonDropdownDto
from typing import Optional, Set
from typing_extensions import Self

class OpaProfileListDto(BaseModel):
    """
    OpaProfileListDto
    """ # noqa: E501
    id: Optional[StrictInt]
    name: Optional[StrictStr]
    forbid_node_port: Optional[StrictBool] = Field(alias="forbidNodePort")
    forbid_http_ingress: Optional[StrictBool] = Field(alias="forbidHttpIngress")
    require_probe: Optional[StrictBool] = Field(alias="requireProbe")
    unique_ingresses: Optional[StrictBool] = Field(alias="uniqueIngresses")
    unique_service_selector: Optional[StrictBool] = Field(alias="uniqueServiceSelector")
    force_pod_resource: Optional[StrictBool] = Field(alias="forcePodResource")
    is_node_name_forbidden_in_vc: Optional[StrictBool] = Field(alias="isNodeNameForbiddenInVC")
    is_master_taint_enforced: Optional[StrictBool] = Field(alias="isMasterTaintEnforced")
    whitelist_master_taint_namespaces: List[StrictStr] = Field(alias="whitelistMasterTaintNamespaces")
    allowed_repo: List[StrictStr] = Field(alias="allowedRepo")
    forbid_specific_tags: List[StrictStr] = Field(alias="forbidSpecificTags")
    ingress_whitelist: List[StrictStr] = Field(alias="ingressWhitelist")
    is_locked: Optional[StrictBool] = Field(alias="isLocked")
    revision: Optional[StrictInt]
    organization_id: Optional[StrictInt] = Field(alias="organizationId")
    organization_name: Optional[StrictStr] = Field(alias="organizationName")
    created_at: Optional[StrictStr] = Field(alias="createdAt")
    is_default: Optional[StrictBool] = Field(alias="isDefault")
    projects: List[CommonDropdownDto]
    __properties: ClassVar[List[str]] = ["id", "name", "forbidNodePort", "forbidHttpIngress", "requireProbe", "uniqueIngresses", "uniqueServiceSelector", "forcePodResource", "isNodeNameForbiddenInVC", "isMasterTaintEnforced", "whitelistMasterTaintNamespaces", "allowedRepo", "forbidSpecificTags", "ingressWhitelist", "isLocked", "revision", "organizationId", "organizationName", "createdAt", "isDefault", "projects"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpaProfileListDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in projects (list)
        _items = []
        if self.projects:
            for _item_projects in self.projects:
                if _item_projects:
                    _items.append(_item_projects.to_dict())
            _dict['projects'] = _items
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpaProfileListDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "forbidNodePort": obj.get("forbidNodePort"),
            "forbidHttpIngress": obj.get("forbidHttpIngress"),
            "requireProbe": obj.get("requireProbe"),
            "uniqueIngresses": obj.get("uniqueIngresses"),
            "uniqueServiceSelector": obj.get("uniqueServiceSelector"),
            "forcePodResource": obj.get("forcePodResource"),
            "isNodeNameForbiddenInVC": obj.get("isNodeNameForbiddenInVC"),
            "isMasterTaintEnforced": obj.get("isMasterTaintEnforced"),
            "whitelistMasterTaintNamespaces": obj.get("whitelistMasterTaintNamespaces"),
            "allowedRepo": obj.get("allowedRepo"),
            "forbidSpecificTags": obj.get("forbidSpecificTags"),
            "ingressWhitelist": obj.get("ingressWhitelist"),
            "isLocked": obj.get("isLocked"),
            "revision": obj.get("revision"),
            "organizationId": obj.get("organizationId"),
            "organizationName": obj.get("organizationName"),
            "createdAt": obj.get("createdAt"),
            "isDefault": obj.get("isDefault"),
            "projects": [CommonDropdownDto.from_dict(_item) for _item in obj["projects"]] if obj.get("projects") is not None else None
        })
        return _obj


