# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OpenStackRegionListQuery(BaseModel):
    """
    OpenStackRegionListQuery
    """ # noqa: E501
    open_stack_user: Optional[StrictStr] = Field(default=None, alias="openStackUser")
    open_stack_password: Optional[StrictStr] = Field(default=None, alias="openStackPassword")
    open_stack_url: Optional[StrictStr] = Field(default=None, alias="openStackUrl")
    open_stack_domain: Optional[StrictStr] = Field(default=None, alias="openStackDomain")
    application_cred_enabled: Optional[StrictBool] = Field(default=None, alias="applicationCredEnabled")
    is_admin: Optional[StrictBool] = Field(default=None, alias="isAdmin")
    __properties: ClassVar[List[str]] = ["openStackUser", "openStackPassword", "openStackUrl", "openStackDomain", "applicationCredEnabled", "isAdmin"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenStackRegionListQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if open_stack_user (nullable) is None
        # and model_fields_set contains the field
        if self.open_stack_user is None and "open_stack_user" in self.model_fields_set:
            _dict['openStackUser'] = None

        # set to None if open_stack_password (nullable) is None
        # and model_fields_set contains the field
        if self.open_stack_password is None and "open_stack_password" in self.model_fields_set:
            _dict['openStackPassword'] = None

        # set to None if open_stack_url (nullable) is None
        # and model_fields_set contains the field
        if self.open_stack_url is None and "open_stack_url" in self.model_fields_set:
            _dict['openStackUrl'] = None

        # set to None if open_stack_domain (nullable) is None
        # and model_fields_set contains the field
        if self.open_stack_domain is None and "open_stack_domain" in self.model_fields_set:
            _dict['openStackDomain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenStackRegionListQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "openStackUser": obj.get("openStackUser"),
            "openStackPassword": obj.get("openStackPassword"),
            "openStackUrl": obj.get("openStackUrl"),
            "openStackDomain": obj.get("openStackDomain"),
            "applicationCredEnabled": obj.get("applicationCredEnabled"),
            "isAdmin": obj.get("isAdmin")
        })
        return _obj


