# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from taikunpycore.models.list_for_partners_dto import ListForPartnersDto
from typing import Optional, Set
from typing_extensions import Self

class PrivateSubscriptionList(BaseModel):
    """
    PrivateSubscriptionList
    """ # noqa: E501
    data: Optional[List[ListForPartnersDto]]
    total_count: Optional[StrictInt] = Field(alias="totalCount")
    is_eligible_to_switch: Optional[StrictBool] = Field(alias="isEligibleToSwitch")
    active_subscription_status: Optional[StrictStr] = Field(alias="activeSubscriptionStatus")
    __properties: ClassVar[List[str]] = ["data", "totalCount", "isEligibleToSwitch", "activeSubscriptionStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrivateSubscriptionList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        # set to None if active_subscription_status (nullable) is None
        # and model_fields_set contains the field
        if self.active_subscription_status is None and "active_subscription_status" in self.model_fields_set:
            _dict['activeSubscriptionStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrivateSubscriptionList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": [ListForPartnersDto.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "totalCount": obj.get("totalCount"),
            "isEligibleToSwitch": obj.get("isEligibleToSwitch"),
            "activeSubscriptionStatus": obj.get("activeSubscriptionStatus")
        })
        return _obj


