# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.kubernetes_resources_dto import KubernetesResourcesDto

class TestKubernetesResourcesDto(unittest.TestCase):
    """KubernetesResourcesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesResourcesDto:
        """Test KubernetesResourcesDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesResourcesDto`
        """
        model = KubernetesResourcesDto()
        if include_optional:
            return KubernetesResourcesDto(
                pods = 56,
                crds = 56,
                helmreleases = 56,
                daemon_sets = 56,
                deployments = 56,
                stateful_sets = 56,
                jobs = 56,
                cron_jobs = 56,
                config_maps = 56,
                namespaces = 56,
                nodes = 56,
                pvcs = 56,
                secrets = 56,
                services = 56,
                ingresses = 56,
                network_policies = 56,
                pdbs = 56,
                storage_classes = 56
            )
        else:
            return KubernetesResourcesDto(
                pods = 56,
                crds = 56,
                helmreleases = 56,
                daemon_sets = 56,
                deployments = 56,
                stateful_sets = 56,
                jobs = 56,
                cron_jobs = 56,
                config_maps = 56,
                namespaces = 56,
                nodes = 56,
                pvcs = 56,
                secrets = 56,
                services = 56,
                ingresses = 56,
                network_policies = 56,
                pdbs = 56,
                storage_classes = 56,
        )
        """

    def testKubernetesResourcesDto(self):
        """Test KubernetesResourcesDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
