# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.partners_api import PartnersApi


class TestPartnersApi(unittest.TestCase):
    """PartnersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartnersApi()

    def tearDown(self) -> None:
        pass

    def test_partner_add_organizations(self) -> None:
        """Test case for partner_add_organizations

        Add organizations to a partner
        """
        pass

    def test_partner_add_whitelist_domain(self) -> None:
        """Test case for partner_add_whitelist_domain

        Add white list domain
        """
        pass

    def test_partner_become_a_partner(self) -> None:
        """Test case for partner_become_a_partner

        Become a partner
        """
        pass

    def test_partner_contact_us(self) -> None:
        """Test case for partner_contact_us

        Contact with us
        """
        pass

    def test_partner_create(self) -> None:
        """Test case for partner_create

        Add a partner
        """
        pass

    def test_partner_delete_organizations(self) -> None:
        """Test case for partner_delete_organizations

        Delete organizations from a partner
        """
        pass

    def test_partner_delete_whitelist_domain(self) -> None:
        """Test case for partner_delete_whitelist_domain

        Delete white list domain
        """
        pass

    def test_partner_details(self) -> None:
        """Test case for partner_details

        Details of partners
        """
        pass

    def test_partner_dropdown(self) -> None:
        """Test case for partner_dropdown

        Get partners dropdown
        """
        pass

    def test_partner_info(self) -> None:
        """Test case for partner_info

        Get partner's registration info
        """
        pass

    def test_partner_list(self) -> None:
        """Test case for partner_list

        Get partners
        """
        pass

    def test_partner_update(self) -> None:
        """Test case for partner_update

        Edit partner's data by Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
