# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.openshift_api import OpenshiftApi


class TestOpenshiftApi(unittest.TestCase):
    """OpenshiftApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenshiftApi()

    def tearDown(self) -> None:
        pass

    def test_openshift_create(self) -> None:
        """Test case for openshift_create

        Add Openshift cloud credential
        """
        pass

    def test_openshift_list(self) -> None:
        """Test case for openshift_list

        Retrieve all operation credentials
        """
        pass

    def test_openshift_pull_secret(self) -> None:
        """Test case for openshift_pull_secret

        Validate openshift pull secret
        """
        pass

    def test_openshift_storage_class(self) -> None:
        """Test case for openshift_storage_class

        Get openshift storage class list
        """
        pass

    def test_openshift_validate(self) -> None:
        """Test case for openshift_validate

        Validate openshift kube config file
        """
        pass


if __name__ == '__main__':
    unittest.main()
