# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.project_group_details_list_dto import ProjectGroupDetailsListDto

class TestProjectGroupDetailsListDto(unittest.TestCase):
    """ProjectGroupDetailsListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGroupDetailsListDto:
        """Test ProjectGroupDetailsListDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGroupDetailsListDto`
        """
        model = ProjectGroupDetailsListDto()
        if include_optional:
            return ProjectGroupDetailsListDto(
                id = 56,
                name = '',
                organization_id = 56,
                organization_name = '',
                projects = [
                    taikunpycore.models.project_list_dto.ProjectListDto(
                        id = 56, 
                        name = '', )
                    ],
                user_groups = [
                    taikunpycore.models.user_group_entity_list_dto.UserGroupEntityListDto(
                        id = 56, 
                        name = '', )
                    ]
            )
        else:
            return ProjectGroupDetailsListDto(
                id = 56,
                name = '',
                organization_id = 56,
                organization_name = '',
                projects = [
                    taikunpycore.models.project_list_dto.ProjectListDto(
                        id = 56, 
                        name = '', )
                    ],
                user_groups = [
                    taikunpycore.models.user_group_entity_list_dto.UserGroupEntityListDto(
                        id = 56, 
                        name = '', )
                    ],
        )
        """

    def testProjectGroupDetailsListDto(self):
        """Test ProjectGroupDetailsListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
