# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.checker_api import CheckerApi


class TestCheckerApi(unittest.TestCase):
    """CheckerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckerApi()

    def tearDown(self) -> None:
        pass

    def test_checker_artifact(self) -> None:
        """Test case for checker_artifact

        Check artifact url
        """
        pass

    def test_checker_aws(self) -> None:
        """Test case for checker_aws

        Check aws credential
        """
        pass

    def test_checker_azure(self) -> None:
        """Test case for checker_azure

        Check azure credentials
        """
        pass

    def test_checker_azure_quota(self) -> None:
        """Test case for checker_azure_quota

        Check azure cpu quota
        """
        pass

    def test_checker_cidr(self) -> None:
        """Test case for checker_cidr

        Check valid cidr format
        """
        pass

    def test_checker_cron(self) -> None:
        """Test case for checker_cron

        Check valid cron job format
        """
        pass

    def test_checker_dns(self) -> None:
        """Test case for checker_dns

        Check valid dns format
        """
        pass

    def test_checker_duplicate_name(self) -> None:
        """Test case for checker_duplicate_name

        Duplicate name
        """
        pass

    def test_checker_google(self) -> None:
        """Test case for checker_google

        Check google credentials
        """
        pass

    def test_checker_helm(self) -> None:
        """Test case for checker_helm

        Check helm credential
        """
        pass

    def test_checker_import_cluster_kube_config(self) -> None:
        """Test case for checker_import_cluster_kube_config

        Check kube config
        """
        pass

    def test_checker_keycloak(self) -> None:
        """Test case for checker_keycloak

        Check keycloak credential
        """
        pass

    def test_checker_kube_config(self) -> None:
        """Test case for checker_kube_config

        Check kube config
        """
        pass

    def test_checker_node(self) -> None:
        """Test case for checker_node

        Duplicate server name checker
        """
        pass

    def test_checker_ntp(self) -> None:
        """Test case for checker_ntp

        Check valid ntp format
        """
        pass

    def test_checker_open_ai(self) -> None:
        """Test case for checker_open_ai

        Check open-ai token
        """
        pass

    def test_checker_openstack(self) -> None:
        """Test case for checker_openstack

        Check openstack credential
        """
        pass

    def test_checker_openstack_taikun_image(self) -> None:
        """Test case for checker_openstack_taikun_image

        Check openstack taikun image
        """
        pass

    def test_checker_openstack_taikun_lb_image(self) -> None:
        """Test case for checker_openstack_taikun_lb_image

        Check openstack taikun lb image
        """
        pass

    def test_checker_organization(self) -> None:
        """Test case for checker_organization

        Check duplicate org name
        """
        pass

    def test_checker_prometheus(self) -> None:
        """Test case for checker_prometheus

        Check prometheus credentials
        """
        pass

    def test_checker_proxmox(self) -> None:
        """Test case for checker_proxmox

        Check proxmox credential
        """
        pass

    def test_checker_s3(self) -> None:
        """Test case for checker_s3

        Check s3 credential
        """
        pass

    def test_checker_ssh(self) -> None:
        """Test case for checker_ssh

        Check valid ssh key format
        """
        pass

    def test_checker_tanzu(self) -> None:
        """Test case for checker_tanzu

        Check tanzu credential
        """
        pass

    def test_checker_user(self) -> None:
        """Test case for checker_user

        Check duplicate username
        """
        pass

    def test_checker_yaml(self) -> None:
        """Test case for checker_yaml

        Check yaml file
        """
        pass

    def test_checker_zadara(self) -> None:
        """Test case for checker_zadara

        Check zadara credential
        """
        pass

    def test_checker_zededa(self) -> None:
        """Test case for checker_zededa

        Check zededa credential
        """
        pass


if __name__ == '__main__':
    unittest.main()
