# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.create_aws_cloud_command import CreateAwsCloudCommand

class TestCreateAwsCloudCommand(unittest.TestCase):
    """CreateAwsCloudCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAwsCloudCommand:
        """Test CreateAwsCloudCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAwsCloudCommand`
        """
        model = CreateAwsCloudCommand()
        if include_optional:
            return CreateAwsCloudCommand(
                name = '',
                aws_secret_access_key = '',
                aws_access_key_id = '',
                az_count = 56,
                aws_region = '',
                organization_id = 56
            )
        else:
            return CreateAwsCloudCommand(
        )
        """

    def testCreateAwsCloudCommand(self):
        """Test CreateAwsCloudCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
