# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.kubernetes_cron_job_dto import KubernetesCronJobDto

class TestKubernetesCronJobDto(unittest.TestCase):
    """KubernetesCronJobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesCronJobDto:
        """Test KubernetesCronJobDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesCronJobDto`
        """
        model = KubernetesCronJobDto()
        if include_optional:
            return KubernetesCronJobDto(
                metadata_name = '',
                last_schedule = '',
                suspend = True,
                schedule = '',
                namespace = '',
                age = ''
            )
        else:
            return KubernetesCronJobDto(
                metadata_name = '',
                last_schedule = '',
                suspend = True,
                schedule = '',
                namespace = '',
                age = '',
        )
        """

    def testKubernetesCronJobDto(self):
        """Test KubernetesCronJobDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
