# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.project_extend_life_time_command import ProjectExtendLifeTimeCommand

class TestProjectExtendLifeTimeCommand(unittest.TestCase):
    """ProjectExtendLifeTimeCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectExtendLifeTimeCommand:
        """Test ProjectExtendLifeTimeCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectExtendLifeTimeCommand`
        """
        model = ProjectExtendLifeTimeCommand()
        if include_optional:
            return ProjectExtendLifeTimeCommand(
                project_id = 56,
                expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                delete_on_expiration = True
            )
        else:
            return ProjectExtendLifeTimeCommand(
        )
        """

    def testProjectExtendLifeTimeCommand(self):
        """Test ProjectExtendLifeTimeCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
