# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.project_catalog_dto import ProjectCatalogDto

class TestProjectCatalogDto(unittest.TestCase):
    """ProjectCatalogDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCatalogDto:
        """Test ProjectCatalogDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCatalogDto`
        """
        model = ProjectCatalogDto()
        if include_optional:
            return ProjectCatalogDto(
                id = 56,
                name = '',
                kubernetes_version = '',
                is_locked = True,
                maintenance_mode_enabled = True,
                is_virtual_cluster = True,
                cloud_type = 'NONE',
                status = 'Null',
                health = 'Null'
            )
        else:
            return ProjectCatalogDto(
        )
        """

    def testProjectCatalogDto(self):
        """Test ProjectCatalogDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
