# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.servers_for_billing_dto import ServersForBillingDto

class TestServersForBillingDto(unittest.TestCase):
    """ServersForBillingDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServersForBillingDto:
        """Test ServersForBillingDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServersForBillingDto`
        """
        model = ServersForBillingDto()
        if include_optional:
            return ServersForBillingDto(
                cpu = 56,
                ram = 56
            )
        else:
            return ServersForBillingDto(
                cpu = 56,
                ram = 56,
        )
        """

    def testServersForBillingDto(self):
        """Test ServersForBillingDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
