# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.unbind_flavor_from_project_command import UnbindFlavorFromProjectCommand

class TestUnbindFlavorFromProjectCommand(unittest.TestCase):
    """UnbindFlavorFromProjectCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnbindFlavorFromProjectCommand:
        """Test UnbindFlavorFromProjectCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnbindFlavorFromProjectCommand`
        """
        model = UnbindFlavorFromProjectCommand()
        if include_optional:
            return UnbindFlavorFromProjectCommand(
                ids = [
                    56
                    ]
            )
        else:
            return UnbindFlavorFromProjectCommand(
        )
        """

    def testUnbindFlavorFromProjectCommand(self):
        """Test UnbindFlavorFromProjectCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
