# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.instance_app_list_dto import InstanceAppListDto

class TestInstanceAppListDto(unittest.TestCase):
    """InstanceAppListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceAppListDto:
        """Test InstanceAppListDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceAppListDto`
        """
        model = InstanceAppListDto()
        if include_optional:
            return InstanceAppListDto(
                id = 56,
                name = '',
                namespace = '',
                status = 'None',
                version = '',
                catalog_id = 56,
                catalog_name = '',
                catalog_app_name = '',
                catalog_app_id = 56,
                app_repo_name = '',
                logo = '',
                auto_sync = True,
                created = '',
                created_by = '',
                last_modified = '',
                last_modified_by = '',
                project_id = 56,
                project_name = '',
                logs = ''
            )
        else:
            return InstanceAppListDto(
                id = 56,
                name = '',
                namespace = '',
                status = 'None',
                version = '',
                catalog_id = 56,
                catalog_name = '',
                catalog_app_name = '',
                catalog_app_id = 56,
                app_repo_name = '',
                logo = '',
                auto_sync = True,
                created = '',
                created_by = '',
                last_modified = '',
                last_modified_by = '',
                project_id = 56,
                project_name = '',
                logs = '',
        )
        """

    def testInstanceAppListDto(self):
        """Test InstanceAppListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
