# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.slack_configuration_list import SlackConfigurationList

class TestSlackConfigurationList(unittest.TestCase):
    """SlackConfigurationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlackConfigurationList:
        """Test SlackConfigurationList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlackConfigurationList`
        """
        model = SlackConfigurationList()
        if include_optional:
            return SlackConfigurationList(
                data = [
                    taikunpycore.models.slack_configuration_dto.SlackConfigurationDto(
                        id = 56, 
                        name = '', 
                        url = '', 
                        channel = '', 
                        organization_name = '', 
                        organization_id = 56, 
                        slack_type = 'Alert', )
                    ],
                total_count = 56
            )
        else:
            return SlackConfigurationList(
                data = [
                    taikunpycore.models.slack_configuration_dto.SlackConfigurationDto(
                        id = 56, 
                        name = '', 
                        url = '', 
                        channel = '', 
                        organization_name = '', 
                        organization_id = 56, 
                        slack_type = 'Alert', )
                    ],
                total_count = 56,
        )
        """

    def testSlackConfigurationList(self):
        """Test SlackConfigurationList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
