# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.describe_crd_command import DescribeCrdCommand

class TestDescribeCrdCommand(unittest.TestCase):
    """DescribeCrdCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DescribeCrdCommand:
        """Test DescribeCrdCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DescribeCrdCommand`
        """
        model = DescribeCrdCommand()
        if include_optional:
            return DescribeCrdCommand(
                project_id = 56,
                name = ''
            )
        else:
            return DescribeCrdCommand(
        )
        """

    def testDescribeCrdCommand(self):
        """Test DescribeCrdCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
