# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_access_profiles(self) -> None:
        """Test case for search_access_profiles

        Global search for access-profiles
        """
        pass

    def test_search_backup_credentials(self) -> None:
        """Test case for search_backup_credentials

        Global search for backup-credentials
        """
        pass

    def test_search_billing_credentials(self) -> None:
        """Test case for search_billing_credentials

        Global search for billing-credentials
        """
        pass

    def test_search_cloud_credentials(self) -> None:
        """Test case for search_cloud_credentials

        Global search for cloud-credentials
        """
        pass

    def test_search_config_maps(self) -> None:
        """Test case for search_config_maps

        Global search for config-maps
        """
        pass

    def test_search_daemon_sets(self) -> None:
        """Test case for search_daemon_sets

        Global search for daemon-sets
        """
        pass

    def test_search_deployments(self) -> None:
        """Test case for search_deployments

        Global search for deployments
        """
        pass

    def test_search_ingress(self) -> None:
        """Test case for search_ingress

        Global search for ingress
        """
        pass

    def test_search_kubernetes_profiles(self) -> None:
        """Test case for search_kubernetes_profiles

        Global search for kubernetes-profiles
        """
        pass

    def test_search_nodes(self) -> None:
        """Test case for search_nodes

        Global search for nodes
        """
        pass

    def test_search_organizations(self) -> None:
        """Test case for search_organizations

        Global search for organizations
        """
        pass

    def test_search_partners(self) -> None:
        """Test case for search_partners

        Global search for partners
        """
        pass

    def test_search_pods(self) -> None:
        """Test case for search_pods

        Global search for pods
        """
        pass

    def test_search_projects(self) -> None:
        """Test case for search_projects

        Global search for projects
        """
        pass

    def test_search_prometheus_rules(self) -> None:
        """Test case for search_prometheus_rules

        Global search for prometheus-rules
        """
        pass

    def test_search_pvcs(self) -> None:
        """Test case for search_pvcs

        Global search for pvcs
        """
        pass

    def test_search_secrets(self) -> None:
        """Test case for search_secrets

        Global search for secrets
        """
        pass

    def test_search_servers(self) -> None:
        """Test case for search_servers

        Global search for servers
        """
        pass

    def test_search_services(self) -> None:
        """Test case for search_services

        Global search for services
        """
        pass

    def test_search_stand_alone_profiles(self) -> None:
        """Test case for search_stand_alone_profiles

        Global search for stand-alone-profiles
        """
        pass

    def test_search_sts(self) -> None:
        """Test case for search_sts

        Global search for sts
        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        Global search for users
        """
        pass


if __name__ == '__main__':
    unittest.main()
