# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.openstack_volume_type_list_query import OpenstackVolumeTypeListQuery

class TestOpenstackVolumeTypeListQuery(unittest.TestCase):
    """OpenstackVolumeTypeListQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenstackVolumeTypeListQuery:
        """Test OpenstackVolumeTypeListQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenstackVolumeTypeListQuery`
        """
        model = OpenstackVolumeTypeListQuery()
        if include_optional:
            return OpenstackVolumeTypeListQuery(
                project_id = 56,
                open_stack_user = '',
                open_stack_password = '',
                open_stack_url = '',
                open_stack_domain = '',
                open_stack_region = '',
                application_cred_enabled = True,
                is_admin = True,
                openstack_project = ''
            )
        else:
            return OpenstackVolumeTypeListQuery(
        )
        """

    def testOpenstackVolumeTypeListQuery(self):
        """Test OpenstackVolumeTypeListQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
