# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.common_dropdown_is_bound_dto_for_project import CommonDropdownIsBoundDtoForProject

class TestCommonDropdownIsBoundDtoForProject(unittest.TestCase):
    """CommonDropdownIsBoundDtoForProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonDropdownIsBoundDtoForProject:
        """Test CommonDropdownIsBoundDtoForProject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonDropdownIsBoundDtoForProject`
        """
        model = CommonDropdownIsBoundDtoForProject()
        if include_optional:
            return CommonDropdownIsBoundDtoForProject(
                id = 56,
                name = '',
                is_bound = True,
                has_kube_config_file = True,
                kubernetes_version = '',
                is_locked = True,
                maintenance_mode_enabled = True,
                is_virtual_cluster = True,
                alerting_profile_id = 56,
                cloud_type = 'NONE',
                status = 'Null',
                health = 'Null',
                import_cluster_type = 'None'
            )
        else:
            return CommonDropdownIsBoundDtoForProject(
        )
        """

    def testCommonDropdownIsBoundDtoForProject(self):
        """Test CommonDropdownIsBoundDtoForProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
