# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.generic_kubernetes_cloud_credential_api import GenericKubernetesCloudCredentialApi


class TestGenericKubernetesCloudCredentialApi(unittest.TestCase):
    """GenericKubernetesCloudCredentialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenericKubernetesCloudCredentialApi()

    def tearDown(self) -> None:
        pass

    def test_generic_kubernetes_list(self) -> None:
        """Test case for generic_kubernetes_list

        Retrieve list of generic kubernetes cloud credentials
        """
        pass

    def test_generic_kubernetes_update(self) -> None:
        """Test case for generic_kubernetes_update

        Update Generic kubernetes credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
