# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.models.subresource import Subresource

class TestSubresource(unittest.TestCase):
    """Subresource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subresource:
        """Test Subresource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subresource`
        """
        model = Subresource()
        if include_optional:
            return Subresource(
                name = '',
                metadata = {
                    'key' : null
                    },
                hourly_cost = '',
                monthly_cost = '',
                cost_components = [
                    taikunpycore.models.cost_component.CostComponent(
                        name = '', 
                        unit = '', 
                        hourly_quantity = '', 
                        monthly_quantity = '', 
                        price = '', 
                        hourly_cost = '', 
                        monthly_cost = '', 
                        price_not_found = True, 
                        usage_based = True, )
                    ]
            )
        else:
            return Subresource(
        )
        """

    def testSubresource(self):
        """Test Subresource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
