# coding: utf-8

"""
    Taikun - WebApi

    This Api will be responsible for overall data distribution and authorization.

    The version of the OpenAPI document: v1
    Contact: noreply@taikun.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from taikunpycore.api.ticket_api import TicketApi


class TestTicketApi(unittest.TestCase):
    """TicketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TicketApi()

    def tearDown(self) -> None:
        pass

    def test_ticket_archive(self) -> None:
        """Test case for ticket_archive

        Archive ticket
        """
        pass

    def test_ticket_close(self) -> None:
        """Test case for ticket_close

        Close ticket
        """
        pass

    def test_ticket_create(self) -> None:
        """Test case for ticket_create

        Create ticket
        """
        pass

    def test_ticket_delete(self) -> None:
        """Test case for ticket_delete

        Delete ticket
        """
        pass

    def test_ticket_delete_message(self) -> None:
        """Test case for ticket_delete_message

        Delete ticket message
        """
        pass

    def test_ticket_edit(self) -> None:
        """Test case for ticket_edit

        Edit ticket
        """
        pass

    def test_ticket_edit_message(self) -> None:
        """Test case for ticket_edit_message

        Edit ticket message
        """
        pass

    def test_ticket_list(self) -> None:
        """Test case for ticket_list

        Retrieve list of tickets
        """
        pass

    def test_ticket_messages(self) -> None:
        """Test case for ticket_messages

        Retrieve articles of ticket
        """
        pass

    def test_ticket_open(self) -> None:
        """Test case for ticket_open

        Open ticket
        """
        pass

    def test_ticket_reply(self) -> None:
        """Test case for ticket_reply

        Reply message
        """
        pass

    def test_ticket_set_priority(self) -> None:
        """Test case for ticket_set_priority

        Set priority
        """
        pass

    def test_ticket_transfer(self) -> None:
        """Test case for ticket_transfer

        Transfer ticket
        """
        pass

    def test_ticket_transfer_list(self) -> None:
        """Test case for ticket_transfer_list

        Retrieve organization managers
        """
        pass


if __name__ == '__main__':
    unittest.main()
